#!/usr/bin/env node
/**
 * Regenerate pricing.json + src/pricing-data.ts from the source TOML.
 *
 * Usage:
 *   node scripts/gen-pricing.mjs [--toml <path>]
 *
 * Default source: ../customized_agentic_system/src/config/llm_models.toml (that
 * repo sits beside this one). The [pricing_v2] section uses only strings and
 * numbers — no nested tables or arrays — so a line-based state machine parses
 * it without a TOML dependency.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..')

function parseArgs(argv) {
  const args = {}
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--toml') args.toml = argv[++i]
  }
  return args
}

const { toml } = parseArgs(process.argv.slice(2))
const tomlPath = toml ?? resolve(repoRoot, '..', 'customized_agentic_system', 'src', 'config', 'llm_models.toml')

const KEY_MAP = {
  provider: 'provider',
  input_per_m: 'inputPerM',
  output_per_m: 'outputPerM',
  cache_read_per_m: 'cacheReadPerM',
  cache_write_per_m: 'cacheWritePerM',
  cache_write_1h_per_m: 'cacheWrite1hPerM',
  batch_input_per_m: 'batchInputPerM',
  batch_output_per_m: 'batchOutputPerM',
  context_cache_storage_per_m_per_hr: 'contextCacheStoragePerMPerHr',
  effective_date: 'effectiveDate',
  notes: 'notes',
}

function tomlKeyToJson(key) {
  return KEY_MAP[key] ?? key
}

/** Parse only the `[pricing_v2."model-id"]` tables into { modelId: { ...fields } }. */
function parsePricingV2(text) {
  const models = {}
  let current = null
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim()
    if (line === '' || line.startsWith('#')) continue
    const section = /^\[pricing_v2\.("([^"]+)")\]$/.exec(line)
    if (section !== null) {
      current = section[2]
      models[current] = {}
      continue
    }
    if (line.startsWith('[')) {
      current = null // left the pricing_v2 section
      continue
    }
    if (current === null) continue
    const kv = /^([A-Za-z0-9_]+)\s*=\s*(.+)$/.exec(line)
    if (kv === null) continue
    const value = kv[2].trim()
    const parsed = value.startsWith('"')
      ? value.slice(1, value.lastIndexOf('"'))
      : Number(value)
    if (typeof parsed === 'number' && Number.isNaN(parsed)) continue
    models[current][tomlKeyToJson(kv[1])] = parsed
  }
  return models
}

if (!existsSync(tomlPath)) {
  console.error(`source TOML not found: ${tomlPath}`)
  process.exit(1)
}

const text = readFileSync(tomlPath, 'utf8')
const models = parsePricingV2(text)
const registry = {
  version: 1,
  generatedAt: new Date().toISOString(),
  source: 'llm_models.toml [pricing_v2]',
  models,
}

const json = JSON.stringify(registry, null, 2) + '\n'
writeFileSync(resolve(repoRoot, 'pricing.json'), json)

const ts = [
  '// Generated by scripts/gen-pricing.mjs — DO NOT EDIT BY HAND.',
  '// Rebuild: node scripts/gen-pricing.mjs',
  "import type { PricingRegistry } from './pricing.ts'",
  '',
  `export const DEFAULT_PRICING: PricingRegistry = ${JSON.stringify(registry, null, 2)}`,
  '',
].join('\n')
writeFileSync(resolve(repoRoot, 'src', 'pricing-data.ts'), ts)

console.log(
  `generated pricing.json + src/pricing-data.ts from ${tomlPath} `
  + `(${Object.keys(models).length} models)`,
)
