// Generated by scripts/gen-pricing.mjs — DO NOT EDIT BY HAND.
// Rebuild: node scripts/gen-pricing.mjs
import type { PricingRegistry } from './pricing.ts'

export const DEFAULT_PRICING: PricingRegistry = {
  "version": 1,
  "generatedAt": "2026-08-24T00:03:55.139Z",
  "source": "llm_models.toml [pricing_v2]",
  "models": {
    "claude-fable-5": {
      "provider": "anthropic",
      "inputPerM": 10,
      "outputPerM": 50,
      "cacheReadPerM": 1,
      "cacheWritePerM": 12.5,
      "cacheWrite1hPerM": 20,
      "batchInputPerM": 5,
      "batchOutputPerM": 25,
      "effectiveDate": "2026-08-03",
      "notes": "Claude Fable 5; 项目暂未注册 Anthropic provider"
    },
    "claude-haiku-4-5-20251001": {
      "provider": "anthropic",
      "inputPerM": 1,
      "outputPerM": 5,
      "cacheReadPerM": 0.1,
      "cacheWritePerM": 1.25,
      "cacheWrite1hPerM": 2,
      "batchInputPerM": 0.5,
      "batchOutputPerM": 2.5,
      "effectiveDate": "2026-08-03"
    },
    "claude-opus-5": {
      "provider": "anthropic",
      "inputPerM": 5,
      "outputPerM": 25,
      "cacheReadPerM": 0.5,
      "cacheWritePerM": 6.25,
      "cacheWrite1hPerM": 10,
      "batchInputPerM": 2.5,
      "batchOutputPerM": 12.5,
      "effectiveDate": "2026-08-03"
    },
    "claude-sonnet-5": {
      "provider": "anthropic",
      "inputPerM": 2,
      "outputPerM": 10,
      "cacheReadPerM": 0.2,
      "cacheWritePerM": 2.5,
      "cacheWrite1hPerM": 4,
      "batchInputPerM": 1,
      "batchOutputPerM": 5,
      "effectiveDate": "2026-08-03",
      "notes": "Introductory pricing $2/$10; 2026-09-01 后涨至 $3/$15"
    },
    "claude-sonnet-5-standard": {
      "provider": "anthropic",
      "inputPerM": 3,
      "outputPerM": 15,
      "cacheReadPerM": 0.3,
      "cacheWritePerM": 3.75,
      "cacheWrite1hPerM": 6,
      "batchInputPerM": 1.5,
      "batchOutputPerM": 7.5,
      "effectiveDate": "2026-09-01",
      "notes": "Sonnet 5 标准价（2026-09-01 生效）"
    },
    "deepseek-v4-flash": {
      "provider": "deepseek",
      "inputPerM": 0.44,
      "outputPerM": 1.32,
      "cacheReadPerM": 0.014,
      "offPeakFactor": 0.5,
      "effectiveDate": "2026-08-17",
      "notes": "Peak 01:00-04:00 & 06:00-10:00 UTC weekdays; weekends off-peak all day (from 2026-08-23). cache miss=input"
    },
    "deepseek-v4-pro": {
      "provider": "deepseek",
      "inputPerM": 1.32,
      "outputPerM": 3.96,
      "cacheReadPerM": 0.044,
      "offPeakFactor": 0.5,
      "effectiveDate": "2026-08-17",
      "notes": "Peak 01:00-04:00 & 06:00-10:00 UTC weekdays; weekends off-peak all day (from 2026-08-23). cache miss=input"
    },
    "gemini-3-flash-preview": {
      "provider": "gemini",
      "inputPerM": 0.75,
      "outputPerM": 4.5,
      "cacheReadPerM": 0.075,
      "contextCacheStoragePerMPerHr": 1,
      "batchInputPerM": 0.375,
      "batchOutputPerM": 2.25,
      "effectiveDate": "2026-08-03",
      "notes": "旧模型; cache_read 为推算值"
    },
    "gemini-3.1-flash-lite": {
      "provider": "gemini",
      "inputPerM": 0.25,
      "outputPerM": 1.5,
      "cacheReadPerM": 0.025,
      "contextCacheStoragePerMPerHr": 1,
      "batchInputPerM": 0.125,
      "batchOutputPerM": 0.75,
      "effectiveDate": "2026-08-03"
    },
    "gemini-3.1-pro-preview": {
      "provider": "gemini",
      "inputPerM": 2.7,
      "outputPerM": 16.2,
      "cacheReadPerM": 0.27,
      "contextCacheStoragePerMPerHr": 1,
      "batchInputPerM": 1.35,
      "batchOutputPerM": 8.1,
      "effectiveDate": "2026-08-03",
      "notes": "pricing 来自官方 Priority tier; cache_read 为推算值 (10% of input)"
    },
    "gemini-3.5-flash": {
      "provider": "gemini",
      "inputPerM": 1.5,
      "outputPerM": 9,
      "cacheReadPerM": 0.15,
      "contextCacheStoragePerMPerHr": 1,
      "batchInputPerM": 0.75,
      "batchOutputPerM": 4.5,
      "effectiveDate": "2026-08-03"
    },
    "gemini-3.5-flash-lite": {
      "provider": "gemini",
      "inputPerM": 0.3,
      "outputPerM": 2.5,
      "cacheReadPerM": 0.03,
      "contextCacheStoragePerMPerHr": 1,
      "batchInputPerM": 0.15,
      "batchOutputPerM": 1.25,
      "effectiveDate": "2026-08-03"
    },
    "gemini-3.6-flash": {
      "provider": "gemini",
      "inputPerM": 1.5,
      "outputPerM": 7.5,
      "cacheReadPerM": 0.15,
      "contextCacheStoragePerMPerHr": 1,
      "batchInputPerM": 0.75,
      "batchOutputPerM": 3.75,
      "effectiveDate": "2026-08-03",
      "notes": "gemini-3.6-flash; context cache storage $1/M/hr"
    },
    "gpt-5.4": {
      "provider": "openai",
      "inputPerM": 2.5,
      "outputPerM": 15,
      "cacheReadPerM": 0.25,
      "batchInputPerM": 1.25,
      "batchOutputPerM": 7.5,
      "effectiveDate": "2026-08-03",
      "notes": "GPT-5.6 Terra (旧名); Automatic Prompt Caching"
    },
    "gpt-5.4-mini": {
      "provider": "openai",
      "inputPerM": 1,
      "outputPerM": 6,
      "cacheReadPerM": 0.1,
      "batchInputPerM": 0.5,
      "batchOutputPerM": 3,
      "effectiveDate": "2026-08-03",
      "notes": "GPT-5.6 Luna (旧名); llm_models.toml [pricing] 中价格有误"
    },
    "gpt-5.5": {
      "provider": "openai",
      "inputPerM": 5,
      "outputPerM": 30,
      "cacheReadPerM": 0.5,
      "batchInputPerM": 2.5,
      "batchOutputPerM": 15,
      "effectiveDate": "2026-08-03",
      "notes": "GPT-5.6 Sol (旧名); Automatic Prompt Caching"
    },
    "gpt-5.6-luna": {
      "provider": "openai",
      "inputPerM": 1,
      "outputPerM": 6,
      "cacheReadPerM": 0.1,
      "batchInputPerM": 0.5,
      "batchOutputPerM": 3,
      "effectiveDate": "2026-08-03",
      "notes": "GPT-5.6 Luna; 旧名: gpt-5.4-mini"
    },
    "gpt-5.6-sol": {
      "provider": "openai",
      "inputPerM": 5,
      "outputPerM": 30,
      "cacheReadPerM": 0.5,
      "batchInputPerM": 2.5,
      "batchOutputPerM": 15,
      "effectiveDate": "2026-08-03",
      "notes": "GPT-5.6 Sol; 旧名: gpt-5.5"
    },
    "gpt-5.6-terra": {
      "provider": "openai",
      "inputPerM": 2.5,
      "outputPerM": 15,
      "cacheReadPerM": 0.25,
      "batchInputPerM": 1.25,
      "batchOutputPerM": 7.5,
      "effectiveDate": "2026-08-03",
      "notes": "GPT-5.6 Terra; 旧名: gpt-5.4"
    }
  }
}
